import pandas as pd
import numpy as np
accounts_df=pd.read_csv('Task2/Data/ravenstack_accounts.csv')
print(accounts_df.head())
print(accounts_df['account_id'].duplicated().sum())
subs_df=pd.read_csv("Task2/Data/ravenstack_subscriptions.csv")
print(subs_df.head())
print(subs_df['account_id'].duplicated().sum())
churn_df=pd.read_csv("Task2/Data/ravenstack_churn_events.csv")
print(churn_df.head())
print(churn_df['account_id'].duplicated().sum())
df1=subs_df.merge(churn_df,on='account_id',how='left')
print(df1.head())
print(df1['account_id'].duplicated().sum())
print("********************************************************************************************")
# convert date (DO NOT assign to df_subs)
subs_df['start_date'] = pd.to_datetime(subs_df['start_date'])
df_subs = subs_df.sort_values(['account_id', 'start_date'], ascending=[True, False])
df_subs = df_subs.drop_duplicates(subset='account_id', keep='first')
print(df_subs.head())
print(df_subs['account_id'].duplicated().sum())
# keep only unique churned accounts
df_churn = churn_df[['account_id']].drop_duplicates()
df_churn['churn_status'] = 1
print(df_churn.head())
df_main = accounts_df.copy()
df_main = df_main.merge(df_subs, on='account_id', how='left')
df_main = df_main.merge(df_churn, on='account_id', how='left')
df_main['churn_status'] = df_main['churn_status'].fillna(0)
print(df_main.head())
print("-----Churn Rate------")
print(df_main['churn_status'].mean())
print(df_main.columns)

print("-----Churn Rate per Industry------")
print(df_main.groupby('industry')['churn_status'].mean().sort_values(ascending=False))
print("-----Churn Rate by Plan------")
print(df_main.groupby('plan_tier_y')['churn_status'].mean().sort_values(ascending=False))
print("\n----Customers on the Basic plan are more likely to churn, possibly due to limited features or lower engagement. Improving value at the entry-level plan could reduce churn.----\n")
print(churn_df['reason_code'].value_counts())
print('\n----Customers are primarily churning due to lack of features, followed by support and pricing concerns. This suggests the product may not be meeting user expectations in terms of functionality and service quality.----\n')
df_main.to_csv('main.csv', index=False)
churn_df.to_csv('churn_reasons.csv', index=False)
